"""empty message

Revision ID: ce49b8f44dab
Revises: a6d4daaeb1ac
Create Date: 2022-02-06 22:28:10.632766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce49b8f44dab'
down_revision = 'a6d4daaeb1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_book_author', table_name='book')
    op.drop_column('book', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.VARCHAR(length=200), nullable=True))
    op.create_index('ix_book_author', 'book', ['author'], unique=False)
    # ### end Alembic commands ###
